-- Saudization Dashboard — Full Schema + Seed
-- Run this in your Supabase SQL Editor
-- Generated: 2026-06-21T09:22:54.622Z

-- ═══ STEP 1: Create tables ═══
CREATE TABLE IF NOT EXISTS departments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  department_id uuid REFERENCES departments(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(name, department_id)
);

CREATE TABLE IF NOT EXISTS employees (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
  department_id uuid REFERENCES departments(id) ON DELETE CASCADE,
  position_title text NOT NULL,
  nationality text NOT NULL,
  is_saudi boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Disable RLS (for internal dashboard use)
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;

-- ═══ STEP 2: Department ═══
INSERT INTO departments (name) VALUES ('Managed_Services') ON CONFLICT (name) DO NOTHING;

-- ═══ STEP 3: Teams (4 subcontractor companies) ═══
INSERT INTO teams (department_id, name) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), 'شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة') ON CONFLICT (name, department_id) DO NOTHING;
INSERT INTO teams (department_id, name) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), 'شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله') ON CONFLICT (name, department_id) DO NOTHING;
INSERT INTO teams (department_id, name) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), 'شركة مداد الأفق المحدودة') ON CONFLICT (name, department_id) DO NOTHING;
INSERT INTO teams (department_id, name) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), 'شركة مشاريع الشبكات العربيه') ON CONFLICT (name, department_id) DO NOTHING;

-- ═══ STEP 4: Employees (195 records) ═══
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'عامل إنشاءات', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Logistic Support', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'عامل إنشاءات', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Coordinator-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field   Supervisor-Civil', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Manager', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'مندوب مشتريات', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintenance Engineer-EM', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Optimization Engineer', 'Nigerian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field  Rigger-Civil', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Walk Tester-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project  data entry', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Post Processer', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Desgin -Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Movement Manager', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Manager', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project  data entry', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Walk Tester-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field  Rigger-Civil', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني كهربائي تمديدات كهربائية', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني هندسة اتصالات لاسلكية', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Department secretary', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Desgin -Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Post Processer', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم اتصالات', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintenance Engineer-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'مهندس اتصالات', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Energy Engineer', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'محلل نظم المعلومات', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'مهندس حاسب آلي', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Manager', 'Joradnian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Manager', 'Joradnian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Manager', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني هندسة اتصالات لاسلكية', 'Yemani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Departmrnt deputy', 'Joradnian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني شبكات تقنية معلومات', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني كهربائي شبكات توزيع هوائية', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة انظمةا لاتصالات والالكترونيات المتقدمة مساهمه مختلطه مقفله' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Joradnian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Warehouse Storekeeper', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'مهندس إلكترونيات', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة فرع شركة انظمة ا لاتصالات والالكترونيات المتقدمة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Palasinian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Desgin -Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'عامل إنشاءات', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Walk Tester-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني هندسة اتصالات لاسلكية', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'عامل صيانة أجهزة كهربائية', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم حاسب آلي', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'كهربائي مباني', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Optimization Coordinator', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Walk Tester-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Optimization Coordinator', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project NOC Manager', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني هندسة اتصالات لاسلكية', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم اتصالات', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Asset and data base', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم حاسب آلي', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم حاسب آلي', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Manager', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم حاسب آلي', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Manager', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم حاسب آلي', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Walk Tester-Telecom', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Yemani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني نظم حاسب آلي', 'Joradnian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintenance Engineer-EM', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field  Technical Support Manager', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'كهربائي مباني', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Department Coordinator', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project POD', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Quality Engineer', 'Palasinian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project  data entry', 'Syrian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'فني تدفئة وتهوية وتكييف', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'مهندس كهربائي', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مداد الأفق المحدودة' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Excellance Engineer', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Help desk', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintenance Engineer-EM', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Engineer-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintiance Technician-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Coordinator-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintenance Engineer-EM', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Coordinator-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Warehouse Storekeeper', 'Indian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Desgin -Telecom', 'Philipno', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Coordinator-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Coordinator-Telecom', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'كهربائي مباني', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Safty Officer', 'Pakistani', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'عامل إنشاءات', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Coordinator-Telecom', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Manager', 'Palasinian_Egyptian_Passport', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Field Maintinace Technician-EM', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Logistic Support', 'Sudanese', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Logistic Support', 'Egyptian', false);
INSERT INTO employees (department_id, team_id, position_title, nationality, is_saudi) VALUES ((SELECT id FROM departments WHERE name='Managed_Services'), (SELECT id FROM teams WHERE name='شركة مشاريع الشبكات العربيه' AND department_id=(SELECT id FROM departments WHERE name='Managed_Services')), 'Project Field Region Supervisor', 'Palasinian', false);